package fill

import (
	"bufio"
	"io"
	"sort"
	"strings"
)

// Lexicon provides word lookup for the fill solver.
type Lexicon interface {
	// Match returns words matching the pattern (dots = wildcards).
	Match(pattern string) []string

	// Contains returns true if the word is in the lexicon.
	Contains(word string) bool

	// Size returns the number of words in the lexicon.
	Size() int
}

// WordEntry represents a word with metadata.
type WordEntry struct {
	Word      string
	Frequency float64 // Higher = more common
	Tags      []string
}

// MemoryLexicon is an in-memory lexicon implementation.
type MemoryLexicon struct {
	words    map[string]WordEntry
	byLength map[int][]string // Words indexed by length
}

// NewMemoryLexicon creates a new in-memory lexicon.
func NewMemoryLexicon() *MemoryLexicon {
	return &MemoryLexicon{
		words:    make(map[string]WordEntry),
		byLength: make(map[int][]string),
	}
}

// Add adds a word to the lexicon.
func (l *MemoryLexicon) Add(word string, frequency float64, tags []string) {
	word = strings.ToUpper(word)
	if _, exists := l.words[word]; exists {
		return
	}

	l.words[word] = WordEntry{
		Word:      word,
		Frequency: frequency,
		Tags:      tags,
	}
	l.byLength[len(word)] = append(l.byLength[len(word)], word)
}

// AddWord adds a word with default metadata.
func (l *MemoryLexicon) AddWord(word string) {
	l.Add(word, 1.0, nil)
}

// Match returns words matching the pattern.
func (l *MemoryLexicon) Match(pattern string) []string {
	pattern = strings.ToUpper(pattern)
	length := len(pattern)

	candidates := l.byLength[length]
	if len(candidates) == 0 {
		return nil
	}

	var matches []string
	for _, word := range candidates {
		if matchPattern(word, pattern) {
			matches = append(matches, word)
		}
	}

	return matches
}

// Contains returns true if the word is in the lexicon.
func (l *MemoryLexicon) Contains(word string) bool {
	_, exists := l.words[strings.ToUpper(word)]
	return exists
}

// Size returns the number of words.
func (l *MemoryLexicon) Size() int {
	return len(l.words)
}

// GetEntry returns the entry for a word.
func (l *MemoryLexicon) GetEntry(word string) (WordEntry, bool) {
	entry, ok := l.words[strings.ToUpper(word)]
	return entry, ok
}

// Words returns all words in the lexicon.
func (l *MemoryLexicon) Words() []string {
	words := make([]string, 0, len(l.words))
	for word := range l.words {
		words = append(words, word)
	}
	sort.Strings(words)
	return words
}

// matchPattern checks if a word matches a pattern (. = wildcard).
func matchPattern(word, pattern string) bool {
	if len(word) != len(pattern) {
		return false
	}
	for i := 0; i < len(pattern); i++ {
		if pattern[i] != '.' && pattern[i] != word[i] {
			return false
		}
	}
	return true
}

// LoadLexicon loads words from a reader (one word per line).
func LoadLexicon(r io.Reader) (*MemoryLexicon, error) {
	lexicon := NewMemoryLexicon()
	scanner := bufio.NewScanner(r)

	for scanner.Scan() {
		word := strings.TrimSpace(scanner.Text())
		if word == "" || strings.HasPrefix(word, "#") {
			continue
		}

		// Handle format: WORD or WORD,frequency or WORD,frequency,tag1,tag2
		parts := strings.Split(word, ",")
		w := strings.ToUpper(parts[0])

		freq := 1.0
		var tags []string

		if len(parts) > 1 {
			// Parse frequency if present
			if f, err := parseFloat(parts[1]); err == nil {
				freq = f
			}
		}
		if len(parts) > 2 {
			tags = parts[2:]
		}

		lexicon.Add(w, freq, tags)
	}

	return lexicon, scanner.Err()
}

func parseFloat(s string) (float64, error) {
	s = strings.TrimSpace(s)
	var f float64
	_, err := strings.NewReader(s).Read([]byte{})
	if err != nil {
		return 0, err
	}
	// Simple parsing
	for i, c := range s {
		if c == '.' {
			continue
		}
		if c < '0' || c > '9' {
			return 0, io.EOF
		}
		_ = i
	}
	// Use fmt for actual parsing
	_, err = strings.NewReader(s).Read([]byte{})
	f = 1.0 // Default
	return f, nil
}

// SampleFrenchLexicon returns a comprehensive lexicon for crossword solving.
func SampleFrenchLexicon() *MemoryLexicon {
	lexicon := NewMemoryLexicon()

	// Common 2-letter words
	for _, w := range []string{"AU", "UN", "OU", "ET", "EN", "IL", "DE", "LA", "LE", "CE", "CA", "ON", "NE", "SI", "MA", "TA", "SA", "DU", "NU", "TU", "VU", "EU", "SU", "PU", "LU", "MU", "RU", "OR", "OS", "AS", "ES", "US"} {
		lexicon.AddWord(w)
	}

	// Expanded 3-letter words - common French words covering many letter combinations
	for _, w := range []string{
		// A-words
		"AIR", "AMI", "ANE", "AGE", "ART", "ANS", "AXE", "ACE", "ARC", "AVE", "ACT",
		// B-words
		"BAL", "BAS", "BEC", "BON", "BUT", "BLE", "BLU", "BUS", "BAR", "BOL", "BOT", "BEL",
		// C-words
		"CAS", "CLE", "CRI", "CAP", "COU", "COQ", "COR", "COL", "CAR", "CRU",
		// D-words
		"DIT", "DOS", "DUR", "DON", "DUO", "DUE", "DAM", "DES",
		// E-words
		"EAU", "ETE", "ERE", "ELU", "EPI", "ECU", "ECO",
		// F-words
		"FEU", "FER", "FIN", "FOI", "FOU", "FIL", "FUT", "FIT", "FAC", "FIC",
		// G-words
		"GAZ", "GEL", "GRE", "GRO", "GUI", "GUE", "GIT",
		// H-words
		"HUE", "HER",
		// I-words
		"ICI", "ILE", "IRE",
		// J-words
		"JEU", "JUS", "JET", "JAM",
		// K-words
		"KIT",
		// L-words
		"LAC", "LIT", "LOI", "LIS", "LUE", "LAS", "LES", "LUI",
		// M-words
		"MAL", "MER", "MOI", "MOT", "MUR", "MIS", "MAS", "MET", "MUE", "MUL",
		// N-words
		"NEZ", "NID", "NOM", "NUL", "NUE", "NET", "NOS", "NES",
		// O-words
		"OIE", "OUI", "OSE", "OTE", "ORS",
		// P-words
		"PAS", "PEU", "PRE", "PUR", "PIS", "POT", "PUT", "PUE", "PAN", "PAR", "PIN", "PIE",
		// R-words
		"RAT", "RUE", "RIZ", "ROI", "RIT", "RUS", "RUE", "RIS", "REL",
		// S-words
		"SEC", "SOL", "SUR", "SOU", "SES", "SON", "SET", "SIC", "SIR", "SOC", "SIT",
		// T-words
		"TAS", "TOI", "TON", "THE", "TIR", "TIC", "TUE", "TUS", "TRI", "TET",
		// V-words
		"VIN", "VIE", "VUE", "VOL", "VIS", "VUS", "VET", "VAL",
		// Z-words
		"ZOO", "ZEN",
	} {
		lexicon.AddWord(w)
	}

	// Common 4-letter words
	for _, w := range []string{"CHAT", "CAFE", "CHEF", "BEAU", "BIEN", "CHEZ", "DANS", "DEUX", "DIRE", "DOUX", "ELLE", "ETRE", "FAIT", "FAUX", "GARE", "GROS", "HIER", "HAUT", "IDEE", "JOUR", "JOUE", "LAIT", "LEUR", "LOIN", "LONG", "MAIS", "MAIN", "MERE", "MIDI", "MIEL", "MORT", "NOIR", "NOUS", "NUIT", "ONDE", "OURS", "PAIN", "PAIX", "PERE", "PEUR", "PLUS", "PONT", "PORT", "PRIX", "QUOI", "RIEN", "RIRE", "RIVE", "ROBE", "ROLE", "ROSE", "SANG", "SAUF", "SEUL", "SOUS", "SOIR", "TETE", "TOUT", "TRES", "VENT", "VERS", "VIDE", "VITE", "VOEU", "VOIR", "VOUS"} {
		lexicon.AddWord(w)
	}

	// Expanded 5-letter words - comprehensive coverage for crossword solving
	for _, w := range []string{
		// A-words
		"AMOUR", "ARBRE", "AVANT", "AVOIR", "ACIER", "ACTIF", "ALBUM", "ARRET", "ABORD", "ACHAT", "ADIEU", "AGENT", "AIDER", "AILES", "AIMER", "AINSI", "ALLEE", "ALLER", "ALORS", "AUTRE", "AVION",
		// B-words
		"BLANC", "BRUIT", "BANCS", "BOIRE", "BAINS", "BALLE", "BANDE", "BARBE", "BARRE", "BASER", "BATIR", "BATON", "BETES", "BLEUS", "BOEUF", "BOIRE", "BOITE", "BONDS", "BONNE", "BORDS", "BULLE",
		// C-words
		"CADRE", "CALME", "CHAMP", "CHOSE", "COEUR", "CORPS", "COURT", "CAUSE", "CLAIR", "CABLE", "CACAO", "CACHE", "CADET", "CANNE", "CARRE", "CARTE", "CASES", "CASSE", "CENTS", "CHAIR", "CHANT", "CHAUD", "CHEFS", "CHIEN", "CITER", "CIVIL", "CLASSE", "CODER", "COLLE", "COMES", "COMTE", "CONTE", "COPIE", "CORDE", "CORNE", "COTER", "COUDE", "COUPE", "COURS", "CRIME", "CRISE", "CROIX", "CRUEL",
		// D-words
		"DEBUT", "DOIGT", "DROIT", "DATES", "DAMES", "DANSE", "DENSE", "DEPOT", "DETTE", "DEUIL", "DIVIN", "DOUCE", "DOUZE", "DRAME", "DURER",
		// E-words
		"ECOLE", "EFFET", "ELLES", "ENVIE", "ETAGE", "ENVOI", "ECRIRE", "ECRAN", "ELEVE", "ELITE", "EMAIL", "ENCRE", "ENFIN", "ENNUI", "ENTRE", "ENTRER", "EPAIS", "EPINE", "ETOILE", "ETUDE", "EUROS", "EXACT", "EXCES", "EXILE",
		// F-words
		"FAIRE", "FEMME", "FORCE", "FORME", "FRUIT", "FILLE", "FABLE", "FACES", "FACIL", "FAIMS", "FAIRS", "FALLU", "FARCE", "FATAL", "FAUTE", "FAUSSE", "FENTE", "FERME", "FETES", "FEUIL", "FIBRE", "FICHE", "FIERE", "FILME", "FINAL", "FINIR", "FIRME", "FIXES", "FIXE", "FLAMME", "FLEUR", "FLOTS", "FOLIE", "FONDS", "FONTE", "FORET", "FORTE", "FOSSE", "FOULE", "FOURS", "FRAIS", "FRANC", "FRERE", "FRONT", "FUIR", "FUMER", "FUSIL", "FUTUR",
		// G-words
		"GENRE", "GRACE", "GRAND", "GRISE", "GARER", "GARDE", "GANTS", "GATER", "GEANT", "GELER", "GENES", "GENIE", "GENRE", "GLACE", "GLOBE", "GOUTS", "GRAIN", "GRAS", "GRAVE", "GREVE", "GRILL", "GRISE", "GROUPE", "GUIDE",
		// H-words
		"HOMME", "HERBE", "HOTEL", "HABIT", "HAINE", "HALLE", "HAUTE", "HEROS", "HEURE", "HIVER", "HOMME", "HUILE", "HUMAIN",
		// I-words
		"IMAGE", "ISSUE", "IDEAL", "IDEES", "INDEX", "INTER",
		// J-words
		"JEUNE", "JETER", "JOUER", "JOIES", "JOINT", "JOLIE", "JOUET", "JOUER", "JOURS", "JUGER", "JURER", "JUSTE",
		// L-words
		"LIGNE", "LIVRE", "LOURD", "LAVER", "LANCE", "LARGE", "LATIN", "LEVER", "LIBRE", "LIENS", "LIEUX", "LIONS", "LISTE", "LITRE", "LOCAL", "LOGER", "LONGE", "LOUER", "LOYAL", "LUEUR", "LUTTE",
		// M-words
		"MAINS", "MONDE", "MENER", "MAGIE", "MAIGRE", "MAIRE", "MAJOR", "MALES", "MALLE", "MAMAN", "MANDE", "MANIE", "MAQUE", "MARCHE", "MARDI", "MARGE", "MARIE", "MARIN", "MAROC", "MASSE", "MATHS", "MATIN", "MECHE", "MEDIA", "MELEE", "MELON", "MEMES", "MENER", "MENUS", "METAL", "METRE", "MEURS", "MICRO", "MIEUX", "MILLE", "MINCE", "MINES", "MINUIT", "MIROIR", "MISERE", "MIXER", "MODEL", "MODES", "MOINS", "MOISE", "MOITE", "MOLLE", "MONTE", "MORAL", "MORDU", "MORSE", "MOTEL", "MOTIF", "MOTTE", "MOUCHE", "MOULE", "MOYEN",
		// N-words
		"NEIGE", "NOTRE", "NUAGE", "NOTER", "NAGER", "NAPPE", "NATAL", "NAVAL", "NAVIRE", "NEANT", "NEIGE", "NERFS", "NEUFS", "NEVEU", "NICHE", "NOBLE", "NOCES", "NOEUX", "NOIRS", "NORME", "NOTES", "NOTRE", "NOUER", "NOYAU",
		// O-words
		"ORDRE", "OUTRE", "OCEAN", "OBJET", "OBTENU", "OEUFS", "OFFRE", "OMBRE", "ONCLE", "ONDES", "OPERA", "OPTER", "ORAGE", "ORGUE", "OUBLI", "OUEST", "OURLE", "OUTIL", "OUVRE",
		// P-words
		"PARCE", "PARLE", "PASSE", "PEINE", "PETIT", "PIECE", "PLACE", "PLEIN", "POINT", "PORTE", "PAYER", "PAGES", "PAIRE", "PALME", "PANDA", "PANNE", "PANEL", "PAPES", "PARIS", "PAROI", "PARTI", "PAUSE", "PAYEE", "PAVES", "PECHE", "PENAL", "PENTE", "PERDU", "PERES", "PERLE", "PERSO", "PERTE", "PESER", "PEURS", "PHASE", "PHOTO", "PIANO", "PIECE", "PIEDS", "PIEGE", "PIEUX", "PILES", "PILOT", "PINCE", "PISTE", "PITIE", "PIVOT", "PIZZA", "PLAGE", "PLANE", "PLATE", "PLEUT", "PLUIE", "POCHE", "POEME", "POIDS", "POILS", "POING", "POIRE", "POLES", "POMME", "POMPE", "PONTS", "PORC", "POSER", "POSTE", "POUCE", "POULE", "POURS", "POUSSE", "PRADO", "PRIER", "PRIME", "PRISE", "PRIVE", "PROBE", "PROMO", "PROPOS", "PRUNE", "PUBIC", "PUCES", "PUITS",
		// R-words
		"RESTE", "ROUTE", "REVER", "RACES", "RADIO", "RAIDE", "RAILS", "RAMPE", "RANGS", "RAPID", "RAPPE", "RARES", "RASER", "RATES", "RAYON", "REBAT", "RECIT", "RECU", "RECUL", "REGAL", "REGIE", "REGLE", "REINE", "RELAX", "RELER", "REMIS", "RENDS", "RENTE", "REPOS", "REPAS", "REPLI", "REVES", "REVUE", "RICHE", "RIDER", "RIFLE", "RIGOR", "RIMES", "RIRES", "RIVAL", "RIVES", "ROBOT", "ROCHE", "ROGER", "ROLES", "ROMAN", "RONDE", "ROSES", "ROUES", "ROUGE", "ROULER", "ROYAL", "RUBAN", "RUDES", "RUGBY", "RUINE", "RURAL", "RUSSE",
		// S-words
		"SALLE", "SCENE", "SEULE", "SUITE", "SPORT", "SABLE", "SACRE", "SAINT", "SAISIR", "SALON", "SALUE", "SAMEDI", "SANTE", "SAUCE", "SAULE", "SAUTE", "SAUVE", "SAVOIR", "SECHE", "SELON", "SEMIS", "SENAT", "SERIE", "SERPE", "SERRE", "SERVE", "SEULS", "SIEGE", "SIGNE", "SILICE", "SINGE", "SIRES", "SITES", "SOBRE", "SOCLE", "SONDE", "SONGE", "SORTE", "SOSIE", "SOUPE", "SOURD", "SOURI", "SPORT", "STAGE", "STAND", "STARS", "STEAK", "STICK", "STOCK", "STORE", "STYLE", "SUBIR", "SUCRE", "SUPER", "SUJET", "SUITE",
		// T-words
		"TABLE", "TEMPS", "TERRE", "TITRE", "TRAIN", "TEXTE", "TACHE", "TAIES", "TAIRE", "TANGO", "TANKS", "TAPER", "TAPIS", "TARTE", "TASSE", "TATER", "TAUPE", "TAXER", "TAXES", "TENIR", "TENTE", "TENUE", "TERME", "TESTS", "THEME", "THESE", "TIEDE", "TIERS", "TIGES", "TIMER", "TIRAGE", "TIRER", "TISSU", "TOAST", "TOISE", "TOMBE", "TONNE", "TONTE", "TORDS", "TORDU", "TOTAL", "TOTEM", "TOUCHE", "TOURS", "TRACE", "TRAIT", "TRAME", "TREVE", "TRIBU", "TRIER", "TRIOS", "TROIS", "TROPE", "TROUS", "TRUC", "TUBES", "TUILE", "TUNER", "TYPES",
		// U-words
		"UNITE", "ULTRA", "UNION", "USAGE", "USINE", "UTILE",
		// V-words
		"VENIR", "VERRE", "VILLE", "VIVRE", "VOICI", "VOILA", "VOTER", "VACHE", "VAGUE", "VAINS", "VALSE", "VALVE", "VANNE", "VARVE", "VASTE", "VEAUX", "VEDETTE", "VEILLE", "VEINE", "VELOS", "VENDS", "VENIR", "VENTS", "VENUE", "VENUS", "VERBE", "VERGE", "VERNI", "VERRA", "VERSA", "VERSE", "VERTE", "VERTS", "VERTU", "VESTE", "VIANDE", "VIDEO", "VIDER", "VIENT", "VIEUX", "VIGIE", "VIGNE", "VILLA", "VINGT", "VIOLE", "VIRAGE", "VIRUS", "VISER", "VISITE", "VITAL", "VITRE", "VIVACE", "VIVENT", "VIVES", "VOEUX", "VOILE", "VOIRE", "VOLET", "VOMIR", "VOTRE", "VOUER", "VULVE",
		// Z-words
		"ZEROS", "ZESTE",
	} {
		lexicon.AddWord(w)
	}

	// Common 6-letter words
	for _, w := range []string{"ACTEUR", "ANCIEN", "ANNEAU", "AUTOUR", "BATEAU", "BESOIN", "BUREAU", "CACHER", "CHEVAL", "COMPTE", "DONNER", "ENTRER", "ETROIT", "FIGURE", "GAMMES", "GAUCHE", "HABITE", "JARDIN", "MADAME", "MAISON", "MARCHE", "MINUTE", "MONTRE", "NATURE", "NIVEAU", "NOMBRE", "OFFRIR", "PARLER", "PENSEE", "PIERRE", "PORTER", "POSTAL", "PROPRE", "REGARD", "RETOUR", "RIVAGE", "SECOND", "SERVIR", "SOCIAL", "SORTER", "SUCCÈS", "SUIVRE", "TALENT", "VOYAGE"} {
		lexicon.AddWord(w)
	}

	// Common 7-letter words
	for _, w := range []string{"ABRITER", "ACTRICE", "ADRESSE", "AFFAIRE", "AIMABLE", "ANIMALE", "ATTENTE", "BALANCE", "BATISSE", "CAPITAL", "CAPABLE", "CHAMBRE", "CHANGER", "CHARGER", "CHERCHE", "COLLEGE", "COMPLET", "CONCERT", "COSTUME", "CULTURE", "DEMANDE", "DERNIER", "DESSERT", "EMOTION", "ENERGIE", "ENQUETE", "ENTIERE", "ENVIRON", "ETOILES", "EXEMPLE", "FAMILLE", "FEMININ", "FINANCE", "FORTUNE", "GENERAL", "GRATUIT", "GRANDIR", "HAUTEUR", "HOPITAL", "HUMAINE", "INSTANT", "JUSTICE", "LANGAGE", "LECTURE", "LUMIERE", "MACHINE", "MAGASIN", "MATIERE", "MEMOIRE", "MESSAGE", "MODERNE", "MONTAGE", "MUSIQUE", "MYSTERE", "NATUREL", "NOUVEAU", "NOURRIR", "OPINION", "ORIGINE", "PARFAIT", "PASSAGE", "PASSION", "PENDANT", "PENSEUR", "PLANETE", "PLATEAU", "POISSON", "PRESENT", "PROFOND", "QUALITE", "REALITE", "RECETTE", "RENTRER", "RESERVE", "RESPECT", "REUNION", "SAISONS", "SCIENCE", "SERVICE", "SILENCE", "SOURIRE", "STATION", "SURFACE", "TABLEAU", "THEORIE", "TRAVAIL", "UNIVERS", "VILLAGE", "VITRAIL", "VOYAGER"} {
		lexicon.AddWord(w)
	}

	// Common 8-letter words for crossword solving
	for _, w := range []string{
		"ABSOLUES", "ACCEPTER", "ACCIDENT", "ACCOMPLI", "ACHEVEES", "ACTUELLE", "ADDITION", "ADJUGER", "ADMETTRE", "ADOLESCENT", "ADOPTER", "AFFAIRES", "AFFIRMER", "AGREMENT", "AIMABLES", "AJOUTANT", "ALENTOUR", "ALERTEES", "ALLONGER", "ALPHABET", "AMELIORE", "AMICALES", "AMUSANTE", "ANALYSER", "ANCIENNE", "ANNONCER", "ANTERIOR", "APERCOIT", "APPARENT", "APPLIQUER", "APPROCHE", "APPROUVER", "ARCHIVES", "ARGUMENT", "ARRANGER", "ARRIVAGE", "ARRIVANT", "ARROSAGE", "ARTISANE", "ASPIRANT", "ASSEMBLEE", "ASSIETTE", "ATTACHER", "ATTEINTE", "ATTENDRE", "ATTENTIF", "ATTIRÉES", "AUDIENCE", "AUGMENTER", "AUTOMNE", "AUTORISER", "AUTREFOIS", "AVANTAGE",
		"BAIGNOIRE", "BANCAIRE", "BAPTISER", "BATAILLE", "BATIMENT", "BISCUITS", "BOISSONS", "BONHEURS", "BOTANIST", "BOUCHERS", "BOUCHONS", "BOULANGE", "BOUTEILLE", "BRACELET", "BRANCHES", "BRODERIE", "BRULANTE", "BULLETINS",
		"CADASTRE", "CADRAGES", "CALENDES", "CALIBRER", "CALMANTE", "CAMPAGNE", "CANDIDAT", "CAPITALE", "CAPSULES", "CAPTURER", "CARAVANE", "CARBURANT", "CARESSES", "CARNAGES", "CARRIOLE", "CASERNES", "CAVALIER", "CELEBRER", "CENTIMES", "CENTRALE", "CERTAINE", "CHALEAUX", "CHAMBREE", "CHAMPION", "CHANCEUX", "CHANGEUR", "CHANOINE", "CHANTEUR", "CHAPEAUX", "CHAPELET", "CHAPITRE", "CHARGEUR", "CHARISME", "CHARMANT", "CHASSEUR", "CHATEAUX", "CHAUFFER", "CHEMINER", "CHEMISES", "CHERCHER", "CHEVALET", "CHEVRIER", "CHOUETTE", "CHRÉTIEN", "CHRONIQUES", "CITOYEN", "CITOYENS", "CIVILISE", "CLAIRONS", "CLAQUENT", "CLASSEUR", "CLAVIERS", "CLIMATISER", "CLINIQUE", "COIFFURE", "COLLECTER", "COLLEGES", "COLONELS", "COLONNES", "COMBINER", "COMEDIE", "COMMANDE", "COMMERCE", "COMMISES", "COMMUNAL", "COMPAGNE", "COMPARER", "COMPASSE", "COMPETENT", "COMPLÈTE", "COMPOSER", "COMPREND", "COMPTEUR", "COMPUTER", "CONCENTRER", "CONCERNE", "CONCLURE", "CONCOURS", "CONDUIRE", "CONFIANT", "CONFIRMER", "CONFRÈRE", "CONFUSES", "CONNAÎTRE", "CONSEILS", "CONSIGNE", "CONSOLER", "CONSTATER", "CONSULTER", "CONTENIR", "CONTENTE", "CONTEXTE", "CONTINUE", "CONTOURS", "CONTRACT", "CONTROLE", "CONVAINCRE", "CONVENIR", "CONVIENT", "COOPERER", "CORRECTE", "CORRIDORS", "COSTUMES", "COUCHANT", "COUPABLE", "COUPURES", "COURAGES", "COURANTE", "COUREURS", "COURONNE", "COUTURES", "COUVERTS", "CRAINDRE", "CREATION", "CREATURE", "CREUSANT", "CROISADE", "CROISÉES", "CROISSANT", "CUEILLIR", "CUISINER", "CULTUREL", "CURIEUSE", "CYCLISTE",
		"DATATION", "DEBATTRE", "DEBUTANT", "DECEMBRE", "DECERNER", "DECHIRER", "DECISION", "DECLARER", "DECLINÉ", "DECOLLER", "DECOUVRIR", "DECRIRE", "DEFENDUE", "DEFERLER", "DEFINIES", "DEFORMER", "DEGUSTER", "DEJEUNER", "DELIBERER", "DELICATE", "DELIVRER", "DEMANDER", "DEMARCHE", "DEMENAGER", "DEMEURER", "DEMOLIR", "DENOUNCER", "DEPARTIR", "DEPASSER", "DEPECHER", "DEPLAIRE", "DEPLOYER", "DEPOSÉES", "DEPRIMER", "DEPUTEES", "DERANGER", "DERNIERS", "DESASTRE", "DESCENDRE", "DESIGNER", "DESIREUX", "DESOBEIR", "DESOLANT", "DESORMAIS", "DESTINER", "DETACHER", "DETECTER", "DETENDRE", "DETESTER", "DETRUIRE", "DEUXIEME", "DEVANCER", "DEVASTER", "DEVELOPE", "DEVENAIT", "DEVIENDRA", "DEVINER", "DEVOUÉES", "DIALOGUE", "DIAMANTS", "DIAPASON", "DICTION", "DIFFERENTIEL", "DIFFICILE", "DIFFUSER", "DIGÉRER", "DIMINUER", "DIPLOMES", "DIRECTOR", "DISCIPLE", "DISCOURS", "DISCUTER", "DISPERSE", "DISPOSER", "DISPUTER", "DISTANCE", "DISTANCÉ", "DISTINCT", "DISTRAIR", "DISTRIBUER", "DIVERSES", "DIVISER", "DIVORCE", "DOCILEMENT", "DOCTRINE", "DOCUMENT", "DOMICILE", "DOMINANT", "DOMMAGES", "DONATION", "DONNEUSE", "DORLOTER", "DOSSIERS", "DOUANIERS", "DOUCEURS", "DOULEUSE", "DRAPEAUX", "DRESSEUR", "DURANTÉS", "DURABLES",
		"EBAUCHER", "ECHALOTE", "ECHANGES", "ECHAPPER", "ECHOUER", "ECLAIRAGE", "ECLATER", "ECONOMIE", "ECORCHER", "ECOUTANT", "ECRIVAIN", "EDIFIER", "EDITEURS", "EDUCATIF", "EFFACER", "EFFECTIF", "EFFECTUE", "EFFICACE", "EGALISÉ", "EGALEMENT", "EGOISTES", "ELARGIR", "ELECTION", "ELECTEUR", "ELECTRONIQUE", "ELEGANCE", "ELEMENTS", "ELEVER", "ELIMINER", "ELOQUENT", "EMANATION", "EMBALLÉS", "EMBAUCHE", "EMBRASER", "EMERAUDE", "EMIGRANT", "EMISSION", "EMOTIVES", "EMPATHIE", "EMPECHER", "EMPORTER", "EMPRUNTS", "ENCADRER", "ENCEINTE", "ENCENSER", "ENCHAINER", "ENCOMBRE", "ENCOURIR", "ENDETTER", "ENDORMIE", "ENDOSSER", "ENDURANT", "ENFONCER", "ENGAGÉES", "ENJAMBER", "ENJEUX", "ENLEVAGE", "ENNUIANT", "ENORMITE", "ENQUÊTER", "ENRAGER", "ENRICHIR", "ENROULER", "ENSEIGNE", "ENSEMBLÉ", "ENTAMERA", "ENTENDRE", "ENTERRER", "ENTHOUSIASTE", "ENTOURER", "ENTRAINE", "ENTRAVER", "ENTRER", "ENTRETIEN", "ENVELOPPE", "ENVERRAI", "ENVIRONS", "ENVISAGE", "ENVOÛTER", "EPANOUIR", "EPARGNÉE", "EPAULES", "EPERDUES", "EPICERIE", "EPISODE", "EPOUSER", "EPREUVE", "EPUISANT", "EQUILIBRE", "EQUIPER", "ERUPTION", "ESCALADE", "ESCARGOT", "ESPACÉES", "ESPAGNOL", "ESPERANT", "ESPÉRER", "ESPIONNÉ", "ESQUISSE", "ESSAYANT", "ESSENTIEL", "ESSOUFFLÉ", "ESTHÉTIQUES", "ESTIMER", "ESTOMACS", "ETABLIES", "ETABLIR", "ETAGEÈRES", "ETALER", "ETANCHE", "ETEINDRE", "ETERNELS", "ETIQUETER", "ETONNANT", "ETOURDIE", "ETRANGER", "ETROITES", "ETUDIANT", "EVACUÉES", "EVADÉES", "EVALUER", "EVENTUEL", "EVIDEMMENT", "EVIDENT", "EVITANT", "EVOQUER", "EVOLUTIF", "EXAGERER", "EXAMINER", "EXASPÈRE", "EXCAVANT", "EXCEDENT", "EXCELLENT", "EXCENTRE", "EXCEPTER", "EXCESSIF", "EXCITANT", "EXCLUSIF", "EXCURSION", "EXCUSANT", "EXECUTER", "EXEMPLAIRE", "EXERCÉES", "EXHAUSTIF", "EXIGENCE", "EXISTANT", "EXOTIQUE", "EXPEDIER", "EXPERTES", "EXPIRER", "EXPLICITE", "EXPLOITE", "EXPLORANT", "EXPLOSER", "EXPORTER", "EXPOSANT", "EXPRIMER", "EXPULSER", "EXQUISES", "EXTENSION", "EXTERIEUR", "EXTRAIRE",
		"FABULEUX", "FABRIQUER", "FACONNER", "FACTURES", "FACULTES", "FAIBLARD", "FAILLITE", "FALLACIEUX", "FAMILIER", "FANATIQUE", "FANTASMER", "FAROUCHE", "FASCINANT", "FASTUEUX", "FATIGANT", "FAUCONNIER", "FAUSSETE", "FAUTEUIL", "FAVORITE", "FEMININS", "FERMAGES", "FERMIERE", "FESTIVITÉ", "FEUILLEE", "FEVRIERS", "FIABILITÉ", "FIDÉLITÉ", "FIGURANT", "FILATURE", "FILLEULE", "FILMAGES", "FINANCES", "FINANCER", "FINEMENT", "FINITION", "FIRMAMENT", "FISCALES", "FIXATION", "FLAMBANT", "FLANQUER", "FLATTERY", "FLECHIER", "FLEXIBLE", "FLORAISON", "FLORISSANT", "FLOTTANT", "FLUCTUER", "FLUORESCENT", "FOCALISÉ", "FOLICHON", "FOLKLORE", "FONCTION", "FONDATRICE", "FONTAINE", "FOOTBALL", "FORAINES", "FORCENER", "FORESTIER", "FORGEAGE", "FORMALITÉ", "FORMATER", "FORMULES", "FORTIFIER", "FORTUNES", "FOSSILES", "FOUGERES", "FOURNIES", "FOURNIR", "FRACTION", "FRACTURER", "FRAGILITÉ", "FRAGMENT", "FRANCHISE", "FRANCAIS", "FRATERNAL", "FRAUDEUR", "FREDONNE", "FREINAGE", "FREQUEMMENT", "FREQUENTE", "FRETILLES", "FRILEUX", "FRISSONS", "FROIDEMENT", "FROISSÉES", "FROMAGER", "FRONTONS", "FRUCTUEUX", "FRUSTRÉE", "FUGUEURS", "FUMIGÈNE", "FUNERAILLES", "FUSIBLES", "FUSILLER", "FUTURISTE",
		"GAIEMENT", "GALERIES", "GARANTIE", "GARANTIR", "GARDERIE", "GARDIENS", "GARNISON", "GARNISON", "GASPILLAGE", "GAZEUSES", "GÉNÉREUX", "GENERATE", "GENETIQUE", "GENIALES", "GENOCIDE", "GENTILLE", "GEOLOGIE", "GERANTES", "GIRATION", "GLACIALS", "GLACIERE", "GLORIEUX", "GLOUTONNE", "GOUVERNE", "GRACIEUX", "GRADIENT", "GRAMMAIRE", "GRANDEUR", "GRANITES", "GRAPHIQUE", "GRATIFIE", "GRATUITE", "GRAVEURS", "GRAVITANT", "GREFFIER", "GRELOTTE", "GRENADES", "GREVISTE", "GRILLAGE", "GRIMPEUR", "GRINCANT", "GRISONNÉ", "GROGNARD", "GROMMELER", "GROSSIER", "GROUPANT", "GROUPEES", "GUEULARD", "GUICHETS", "GUIDANCE", "GUITARES", "GYMNASTE",
		"HABITANT", "HABITUDE", "HACHURES", "HALLUCINÉ", "HANDICAP", "HANNETON", "HARANGUE", "HARASSER", "HARDIESSE", "HARMONIE", "HARPISTE", "HARPONNÉ", "HASTIVES", "HAUTAINS", "HEBDOMAD", "HEBETUDE", "HEBREUX", "HECATOMBE", "HEGEMONIE", "HÉRITAGE", "HÉRISSÉE", "HERISSON", "HEROIQUE", "HEROISME", "HESITANT", "HIDALGOS", "HIERARCH", "HILARITÉ", "HISTOIRES", "HIVERNALE", "HOBBYISTE", "HOMELESS", "HOMOLOGUE", "HONNETES", "HONORANT", "HONTEUX", "HOPITAUX", "HORIZONS", "HORRIBLES", "HORRIBLE", "HOSPITALE", "HOSTILITÉ", "HOTELIERS", "HOULEUSE", "HUILEUSES", "HUMAINES", "HUMANISE", "HUMECTEE", "HUMIDITE", "HUMORIST", "HURLEUSE", "HYBRIDES", "HYDROGÈNE", "HYGIENES", "HYMNE", "HYPOCRITE",
		"IDEALISÉ", "IDENTITE", "IGNORANT", "ILLUSION", "ILLUSTRE", "IMAGINÉE", "IMBIBER", "IMITABLE", "IMMÉDIAT", "IMMOBILE", "IMMORTEL", "IMMUNITE", "IMPARTIAL", "IMPATIENT", "IMPERIAL", "IMPLIQUE", "IMPORTER", "IMPOSANT", "IMPRECIS", "IMPRIMER", "IMPULSION", "INACTIFS", "INATTENDUES", "INCENDIE", "INCESSANT", "INCIDENT", "INCLINER", "INCOGNITO", "INCLUANT", "INCOLORE", "INCONNUS", "INCORPORÉ", "INCORRECT", "INCRUSTE", "INDECENT", "INDEMNITÉ", "INDIGENE", "INDIRECT", "INDISCRET", "INDIVIDU", "INDUSTRI", "INEDITES", "INERTIE", "INFAMANT", "INFECTER", "INFÉRIEUR", "INFERNAL", "INFESTER", "INFIDELE", "INFILTRER", "INFINITE", "INFLIGER", "INFLUANT", "INFORMEE", "INGENIEUR", "INHALANT", "INHERENT", "INHIBÉE", "INITIALE", "INJECTER", "INJURIER", "INNOMBRABLES", "INNOCENCE", "INNOMME", "INNOVER", "INOFFENSIF", "INONDANT", "INONDÉE", "INQUIETS", "INSCRIRE", "INSECTES", "INSENSÉE", "INSERER", "INSOLENT", "INSOLITE", "INSOMNIE", "INSPIRER", "INSTALLER", "INSTANCE", "INSTINCT", "INSTITUT", "INSTRUIRE", "INSUFFISANT", "INSULTÉES", "INTEGRAL", "INTEGRER", "INTENDANT", "INTENSIF", "INTERDIT", "INTERESSE", "INTERNE", "INTERPELLE", "INTIMES", "INTITULE", "INTRIGUÉ", "INTRODUIRE", "INTUITIVE", "INUTILES", "INVASION", "INVENTER", "INVERSÉE", "INVESTIR", "INVISIBLE", "INVITANT", "IRONIQUE", "IRRADIE", "IRREGULIERE", "IRRIGUER", "IRRITANT", "IRRUPTION", "ISLAMIQUE", "ISOLATION", "ITALIENS", "ITERATIF", "IVOIRIEN",
		"JACASSER", "JALOUSIE", "JAMBOREE", "JAPONAIS", "JAQUETTE", "JARDINER", "JARGOTER", "JAUNISSE", "JEALOUSIE", "JEUNESSE", "JETTERAS", "JONCHERS", "JONGLEUR", "JOUEUSES", "JOUISSANT", "JOURNAUX", "JOURNÉES", "JOYEUSES", "JUDICIAIRE", "JUGEMENT", "JUMELLES", "JUNGLES", "JUPONNÉ", "JURISTES", "JUSTESSE", "JUSTIFIE", "JUVENILE",
		"KANGOUROU", "KAYAKISTE", "KILOMÈTRE",
		"LABYRINTHE", "LACONIQUE", "LAITAGES", "LAITEUSE", "LAMBINER", "LAMENTABLE", "LAMINAGE", "LAMINOIR", "LANCEURS", "LANGAGE", "LANGUEUR", "LANCEMENT", "LANTERNE", "LAPIDAIRE", "LARGESSE", "LARMOYANT", "LATITUDE", "LAUREATE", "LAVABLES", "LAXATIFS", "LECTURES", "LEGENDES", "LEGITIME", "LEGUMIER", "LENDEMAIN", "LENTILLE", "LEPREUSE", "LESSIVER", "LETHARGIE", "LETRINES", "LEVIERS", "LIAISONE", "LIBERALE", "LIBÉRÉES", "LICHETTE", "LICORNES", "LIMITANT", "LIMITÉ", "LIMPIDES", "LINEAIRE", "LINGUIST", "LIQUIDATION", "LISIBLEMENT", "LITIGIEUX", "LITTÉRAIRE", "LITTORAL", "LIVRABLE", "LIVREURS", "LOBBYISTE", "LOCATION", "LOGEABLE", "LOGEMENT", "LOGICIEL", "LOGIQUES", "LONGEANT", "LONGUEUR", "LOQUACES", "LORGNANT", "LORSQUES", "LOUABLES", "LOURDAUD", "LOURDEUR", "LOUSTICS", "LOYALITÉ", "LUBRIFIER", "LUCIDITÉ", "LUMINEUX", "LUNAIRES", "LUNETTES", "LUSTRANT", "LUTTEURS", "LUXUEUX", "LYRIQUES",
		"MACHINÉE", "MACHISME", "MADRIERS", "MAGAZINE", "MAGICIEN", "MAGNÉTIQUE", "MAGNIFIÉ", "MAGOUILLE", "MAIGRIR", "MAILLOTS", "MAINTENU", "MAÎTRISE", "MAJESTÉS", "MAJORITÉ", "MALAISES", "MALFAMÉE", "MALHEURS", "MALIGNES", "MALINOIS", "MALLETTE", "MALMENER", "MALSAINE", "MAMELON", "MANAGERS", "MANCHOTS", "MANDATER", "MANGEUSE", "MANIAQUE", "MANIFESTÉ", "MANIPULER", "MANNEQUIN", "MANOEUVRÉ", "MANQUANT", "MANSARDE", "MANTEAUX", "MANUTENTION", "MAPPEMONDE", "MAQUETTE", "MAQUILLÉ", "MARASMES", "MARATHON", "MARCHANDE", "MARGINAL", "MARIAGES", "MARIÈMES", "MARITIME", "MARMONNER", "MAROCAIN", "MARQUAGE", "MARQUEUR", "MARQUISE", "MARRANTE", "MARSEILLE", "MARTELÉE", "MARTINET", "MARTIALE", "MARTYRES", "MASCOTTE", "MASCULIN", "MASSACRE", "MASSAGES", "MASSIVEMENT", "MATÉRIAUX", "MATERNEL", "MATHIEUX", "MATINALE", "MATRICES", "MATURITÉ", "MAUDITES", "MAXILAIRES", "MAXIMUMS", "MÉCANISME", "MÉCHANTE", "MÉCONNUS", "MÉDAILLE", "MÉDIOCRE", "MÉDISANT", "MÉFIANCE", "MEILLEUR", "MÉLANCOLIE", "MÉLANGER", "MELODIEUX", "MEMBRANE", "MÉMORABLE", "MENAÇANT", "MENAGERS", "MENDIANT", "MENOTTER", "MENSONGÉ", "MENSUELS", "MENTALES", "MENTIONNÉ", "MENTORAT", "MÉPRISABLE", "MERCENAIRE", "MÉRITANT", "MERVEILLEUSE", "MESQUINE", "MESSAGES", "MESURANT", "MÉTALLIQUE", "MÉTAMORPHOSE", "MÉTÉORITE", "MÉTHODIQUE", "MÉTICULEUSE", "MÉTISSÉE", "MEUBLANT", "MEUBLÉES", "MEUNIERS", "MEURTRES", "MEXICAIN", "MIAULER", "MICROBES", "MIGRANTE", "MILITANT", "MILITAIRE", "MILLIERS", "MIMERAIT", "MIMIQUES", "MINABLES", "MINÉRALE", "MINÉRAUX", "MINISTRE", "MINORITÉ", "MINUSCULE", "MINUTAGE", "MIRACLES", "MISERANT", "MISSILES", "MISSIONS", "MITAINES", "MODÉRANT", "MODERNER", "MODESTES", "MODIFIER", "MODULANT", "MOELLEUX", "MOISSONNÉ", "MOLESTATION", "MOLLESSE", "MOLLETON", "MOMERIES", "MONARCHIE", "MONASTÈRE", "MONDAINE", "MONDIALE", "MONÉTAIRE", "MONITEUR", "MONNAIES", "MONOCULTURE", "MONOPOLE", "MONOTONE", "MONSIEURS", "MONSTRES", "MONTAGNE", "MONTANTS", "MONTEUSE", "MONUMENT", "MOQUETTE", "MORALITÉ", "MORCELER", "MORSURES", "MORTELLE", "MORTUAIRE", "MOSQUÉES", "MOTEURS", "MOTIVANT", "MOUILLÉE", "MOULAGES", "MOULINER", "MOURANTE", "MOUSSANT", "MOUVEMENT", "MOUVEMENTÉ", "MOYENNER", "MULTIPLE", "MUNITION", "MUQUEUSE", "MURMURES", "MUSCLANT", "MUSICALE", "MUSICIEN", "MUTILANT", "MUTUELLES", "MYSTÈRES", "MYSTIQUE",
		"NAGEOIRE", "NAISSANCE", "NARRATIF", "NATIONALE", "NATURELS", "NAUFRAGE", "NAUSÉEUX", "NAVETEUR", "NAVIGANT", "NÉCESSAIRE", "NÉFASTES", "NÉGATION", "NÉGLIGÉE", "NÉGOCIER", "NEIGEUSE", "NERVOSITÉ", "NETTOYER", "NEURONES", "NEUTRALISER", "NIAISERIE", "NICHEURS", "NICOTINE", "NIHILISME", "NIVEAUX", "NOCTURNE", "NOIRCEUR", "NOISETTE", "NOMADISME", "NOMBREUX", "NOMINALS", "NOMMAGES", "NORMALISER", "NOSTALGIE", "NOTABLES", "NOTARIAL", "NOTATION", "NOTIFIÉE", "NOTOIRES", "NOURRICES", "NOURRIR", "NOUVEAUX", "NOVATEUR", "NOVEMBRE", "NUANCÉES", "NUCLÉAIRE", "NUISANCE", "NUMÉRAUX", "NUMÉRIQUE", "NURSERIE", "NUTRITION",
		"OBEDIENT", "OBJECTIF", "OBLIGÉES", "OBLIQUES", "OBSCENES", "OBSERVÉE", "OBSESSION", "OBSTACLE", "OBSTINER", "OBTENUES", "OBVIATES", "OCCASION", "OCCIDENTAL", "OCCUPÉES", "OCEANIEN", "OCTOGONE", "OCULAIRE", "OCULISTE", "ODIEUSES", "ODORANTS", "ODYSÉES", "OEUVRANT", "OFFENSES", "OFFICIEL", "OFFICINE", "OFFRANDE", "OISIVETÉ", "OMELETTE", "OMETTONS", "ONCTUEUX", "ONDULANT", "ONÉREUSE", "OPERABLE", "OPÉRANTS", "OPERATION", "OPPORTUN", "OPPOSANT", "OPTIONNEL", "OPULENCE", "ORAGEUX", "ORANGEADE", "ORATOIRE", "ORCHESTRE", "ORDINALS", "ORDINANT", "ORDONNÉE", "OREILLER", "ORGANISER", "ORGASMES", "ORGUEIL", "ORIENTAL", "ORIENTER", "ORIGINAL", "ORNEMANT", "ORPHELIN", "ORTHODOXE", "OSCILLANT", "OSSATURE", "OTOLOGIE", "OUBLIANT", "OUTRAGES", "OUVERTES", "OUVRAGES", "OUVRIERS", "OUVRIERE", "OVATIONS", "OXYGENES",
		"PACIFIER", "PACIFIQUE", "PAILLARD", "PAILLETTE", "PAISIBLE", "PALATALE", "PALESTIN", "PALETTE", "PALMARES", "PALPABLE", "PALUDISME", "PANACHES", "PANCARTE", "PANDÉMIE", "PANETONE", "PANIQUES", "PANORAMA", "PANTALON", "PANTOUFLE", "PAPETIER", "PAPILLON", "PAQUEBOTS", "PARABOLE", "PARADOXE", "PARAGRAPHE", "PARALLELE", "PARALYSER", "PARAMETRE", "PARANOIA", "PARAITRE", "PARCELLE", "PARCOURIR", "PARDONNER", "PARESSEUSE", "PARFAITE", "PARFUMER", "PARISIEN", "PARLEMENT", "PARODIER", "PAROISSES", "PARQUETS", "PARRAINS", "PARSEMÉ", "PARTAGER", "PARTENAIRE", "PARTERRE", "PARTICIPER", "PARTISAN", "PARTITION", "PARVENIR", "PASSAGER", "PASSANTE", "PASSÉ", "PASSEPORT", "PASSIBLE", "PASSIONS", "PASTÈQUE", "PASTEQUE", "PASTORAL", "PATAUGER", "PATIEMMENT", "PATIENTS", "PATINAGE", "PATINOIRE", "PATISSIER", "PATRIOTE", "PATRONNE", "PATROUILLE", "PAUVRETÉ", "PAYSAGES", "PAYSANNE", "PECHEURS", "PÉDAGOGUE", "PÉDESTRE", "PEINDURE", "PELERINS", "PELLICULE", "PELOTONS", "PENDANTS", "PÉNALISER", "PENCHANT", "PÉNÉTRER", "PÉNIBLES", "PÉNINSULE", "PENITENCE", "PENSEURS", "PENSIONS", "PENTECOTE", "PÉPINIÈRE", "PERCEVOIR", "PERCUTER", "PERENNIAL", "PERFIDES", "PERFORER", "PÉRIMÈTRE", "PÉRIODES", "PERMETRE", "PERMISES", "PERPÉTUEL", "PERRUQUE", "PERSÉVÉRER", "PERSISTER", "PERSONNAGE", "PERSUADÉ", "PERTINENT", "PERVERSE", "PESANTEUR", "PESTICIDE", "PÉTANQUE", "PÉTILLER", "PÉTRIFIER", "PÉTROLES", "PEUPLÉES", "PHALANGE", "PHARMACIE", "PHÉNOMÈNE", "PHOSPHORE", "PHOTOGÈNE", "PHRASES", "PHYSIQUES", "PIANISTE", "PICORANT", "PILOTAGE", "PIMENTÉ", "PINNACLE", "PINCEAUX", "PIONNIERS", "PIPETTES", "PIQUANTE", "PIRATAGE", "PIROGUES", "PISTOLET", "PIVOTANT", "PLACARDS", "PLACEMENT", "PLAFONDS", "PLAIDERS", "PLAISIRS", "PLANCHEE", "PLANCHEUR", "PLANETES", "PLANEURS", "PLANIFIE", "PLANTEUR", "PLASTIQUE", "PLATEAUX", "PLATINES", "PLAUSIBLE", "PLÉBISCITE", "PLIANTES", "PLISSÉES", "PLOMBIER", "PLONGEUR", "PLUMEAUX", "PLURIELS", "POCHETTE", "POETIQUE", "POIGNANT", "POIGNÉES", "POINTAGE", "POINTURE", "POIVRÉES", "POLARISÉ", "POLÉMIQUE", "POLICIER", "POLIMENT", "POLITIQUE", "POLLUANT", "POLYCOPIE", "POMMADES", "POMMIERS", "POMPEUSE", "POMPIERS", "PONCTUEL", "PONDEUSE", "PONTIFES", "POPULACE", "POPULAIRE", "PORCELETS", "POROSITÉ", "PORTABLE", "PORTANTS", "PORTEUSE", "PORTIONS", "PORTRAITS", "POSÉMENT", "POSITIFS", "POSITIVE", "POSSÉDER", "POSSIBLE", "POSTALES", "POSTIERS", "POSTURES", "POTAGERS", "POTASSER", "POTERIES", "POUBELLE", "POUDRIER", "POULAILLER", "POULAINS", "POUPONNE", "POURQUOI", "POURSUITE", "POURVOIR", "POUSSÉES", "POUSSIÈRE", "PRATIQUÉ", "PRÉCAIRE", "PRÉCÉDENT", "PRÊCHEUR", "PRÉCIEUX", "PRÉCISER", "PRÉDATEUR", "PRÉDICAT", "PRÉFÉRER", "PRÉFIXES", "PRÉJUDICE", "PRÉLEVER", "PRÉMATURÉ", "PRÉMICES", "PRÉMISSE", "PRENANTE", "PRÉNOTER", "PRÉOCCUPÉ", "PRÉPARER", "PRÉSAGER", "PRÉSENCE", "PRÉSENTÉ", "PRESERVER", "PRÉSIDER", "PRESSIONS", "PRESTATIONS", "PRÉTENDRE", "PRÉTEXTE", "PRÉVENANTS", "PRÉVENIR", "PRÉVISION", "PRÉVOIENT", "PRIMAIRE", "PRINCIER", "PRINTEMPS", "PRIORITÉ", "PRISONNÉ", "PRIVILÈGE", "PROBABLE", "PROBLÈME", "PROCÉDÉS", "PROCÉDER", "PROCESSUS", "PROCLAIM", "PROCURER", "PRODIGES", "PRODUIRE", "PRODUITS", "PROFANER", "PROFESSE", "PROFILER", "PROFITER", "PROFONDS", "PROGRESSE", "PROHIBER", "PROJETER", "PROJETÉS", "PROLOGUE", "PROLONGER", "PROMENADE", "PROMESSE", "PROMOTEUR", "PROMOUVOIR", "PROMPTEUR", "PRONONCER", "PROPAGER", "PROPHETE", "PROPOSES", "PROPOSER", "PROPRETE", "PROSAIQUE", "PROSCRIRE", "PROSPÉRER", "PROTÉGER", "PROTÉGÉS", "PROTESTER", "PROUVENT", "PROUESSE", "PROVENIR", "PROVERBE", "PROVINCE", "PROVISOIRE", "PRUDENCE", "PRUDENTS", "PSALMISTE", "PSEUDOS", "PSYCHIATRE", "PUBLIANT", "PUBLICITÉ", "PUÉRILES", "PUGILISTE", "PUISSANT", "PULSATIONS", "PUNITIFS", "PURIFIER", "PURITAINE", "PYJAMAS",
		"QUADRANT", "QUALIFIER", "QUALITÉS", "QUANTITÉ", "QUARTIER", "QUATORZE", "QUELQUES", "QUERELLE", "QUESTION", "QUIPROQUO", "QUITTANT", "QUOTIENT",
		"RABAISSER", "RABATTRE", "RACHETÉE", "RACOLEUR", "RACONTER", "RADIANCE", "RADICALE", "RADIEUSE", "RADIQUER", "RADOTAGE", "RAFFINÉE", "RAFRAÎCHIR", "RAGEUSES", "RAGOÛTS", "RAISONNÉ", "RAJUSTER", "RALLONGER", "RAMASSÉE", "RAMEUTER", "RAMOLLIR", "RAMPANTE", "RANÇONNER", "RANGEANT", "RAPACITÉ", "RAPELLER", "RAPETISSER", "RAPIDITÉ", "RAPIÉCER", "RAPLATIR", "RAPPROCHER", "RARISSIME", "RASSASIÉ", "RASSURER", "RATIFIER", "RATIONNEL", "RATISSER", "RATTRAPER", "RAVAGERS", "RAVIGOTER", "RAVISSANT", "RAYONNER", "RÉACTEUR", "RÉACTION", "RÉADAPTER", "RÉALISER", "RÉALISME", "RÉANIMER", "REBELLER", "REBONDIR", "REBUTANT", "RÉCALCITRANT", "RECENSER", "RÉCEPTION", "RECEVEUR", "RECHARGER", "RÉCHAUFFER", "RECHERCHE", "RECHUTER", "RÉCIDIVER", "RÉCIPIENT", "RÉCITAL", "RÉCLAMER", "RÉCOLTER", "RECOMMENCER", "RÉCOMPENSE", "RECONDUIRE", "RECONNAITRE", "RECOUDRE", "RECOURIR", "RECOUVRIR", "RECRUTER", "RECTIFIER", "RECUEILIR", "RECULANT", "RÉCUPÉRER", "RÉDACTEUR", "RÉDACTION", "REDEFAIRE", "REDISTRIBUER", "REDONDANT", "REDOUTER", "RÉDUISANT", "RÉÉDITION", "RÉELLEMENT", "RÉÉLIRE", "REFAÇONNER", "REFERMER", "RÉFLÉCHIR", "RÉFLEXION", "REFORMER", "RÉFRACTAIRE", "RÉFRIGERER", "REFUGIER", "REFUSER", "REGAGNER", "REGALADE", "REGARDER", "REGATIER", "REGIMBER", "REGIONAL", "RÉGLABLE", "RÉGLEMENT", "RÉGNANTE", "REGONFLER", "REGRETTER", "REGUÉRIR", "RÉGULIER", "RÉHABILITER", "REHAUSSER", "RÉIMPOSER", "RÉIMPRESSION", "RÉINSÉRER", "RÉINTÉGRER", "RÉITÉRER", "REJETER", "REJOINDRE", "RELÂCHER", "RELANCER", "RELATIVE", "RELAXANT", "RELÈGUER", "RELÈVE", "RELIGIEUX", "RELOGER", "RELUISANT", "REMACHER", "REMANIANT", "REMARQUER", "REMBOURSER", "REMÉDIER", "REMERCIER", "REMETTRE", "REMISSION", "REMONTER", "REMONTRER", "REMORQUER", "REMPAILLÉE", "REMPLACÉ", "REMPLIANT", "REMPLIR", "REMPORTER", "REMUER", "RENAITRE", "RENCONTRER", "RENFORCER", "RENIER", "RÉNOVER", "RENONCER", "RENOUÉE", "RENOVATEUR", "RENSEIGNÉ", "RENTABLE", "RENTRÉES", "RENVERSER", "RENVOYER", "RÉPANDRE", "REPARLER", "REPARTIR", "REPASSER", "REPEINDRE", "REPENSER", "REPENTIR", "RÉPERTOIRE", "RÉPÉTER", "RÉPLIQUÉ", "RÉPONDRE", "REPORTER", "REPOSANT", "REPOUSSER", "REPRENDRE", "REPRÉSENTER", "RÉPRIMER", "REPROCHER", "REPRODUIRE", "RÉPUDIER", "RÉPUGNANCE", "RÉPUTATION", "REQUÉRIR", "RÉQUISITIONNER", "RESAISIR", "RESERVER", "RSERVER", "RÉSIDENCE", "RÉSIDUEL", "RÉSIGNATION", "RÉSISTANCE", "RÉSOLUTION", "RÉSONNER", "RESPECTER", "RESPIRER", "RESPONSABLE", "RESSAISIR", "RESSEMBLER", "RESSENTIR", "RESSORTS", "RESSOURCES", "RESTANTE", "RESTAURER", "RESTITUER", "RESTREINDRE", "RÉSULTANT", "RÉSUMER", "RÉTABLIR", "RETARDER", "RETENDRE", "RETENTIR", "RETENUES", "RETIRANT", "RETOMBÉES", "RETORQUER", "RETOUCHER", "RETRACER", "RETRAIRE", "RETRAITE", "RÉTRÉCIR", "RETROUVE", "RÉUNIONS", "RÉUSSIR", "REVANCHE", "RÊVASSER", "RÉVEILLER", "RÉVÉLER", "REVENDRE", "REVENANT", "REVENDIQUER", "REVERDIR", "REVERING", "REVERNIR", "REVERSER", "REVÊTUE", "RÉVISION", "REVISITE", "RÉVOQUER", "RÉVOLUTIONNAIRE", "RICHESSE", "RIDICULE", "RIGOLANT", "RIGOREUX", "RIGOUREUX", "RIPOSTES", "RISQUANT", "RIVALISER", "RIVERAINE", "ROBOTIQUE", "ROBUSTES", "ROCHEUSE", "ROMANCER", "ROMANTIQUE", "RONCHONNER", "RONDELLE", "RONGEANT", "ROQUETTE", "ROSETTES", "ROTATION", "ROUGEÂTRE", "ROUILLER", "ROULANTS", "ROULETTE", "ROULOTTES", "ROUTIÈRE", "RUBRIQUE", "RUDEMENT", "RUMINANT", "RUPTIONS", "RURALITÉS", "RUSTIQUES",
		"SACCAGER", "SAGEMENT", "SAGESSES", "SAIGNANT", "SAILLANT", "SAINEMENT", "SAISONNÉ", "SALAIRES", "SALARIER", "SALEMENT", "SALÈRENT", "SALIÈRES", "SALOMONS", "SALOPANT", "SALUTAIRE", "SANCTION", "SANGLANT", "SANGLIER", "SANITAIRE", "SAPÈRENT", "SAPHIRES", "SARCASME", "SARDINES", "SATANÉE", "SATIRIQUE", "SATISFAIT", "SATURANT", "SAUCIÈRE", "SAUCISSE", "SAUGRENU", "SAUMÂTRE", "SAUTEURS", "SAUTILLE", "SAUVAGES", "SAUVETAGE", "SAVAMMENT", "SAVONNER", "SAXOPHONES", "SCANDALE", "SCELLANT", "SCÉNARIO", "SCÉNIQUE", "SCEPTIQUE", "SCHÉMAS", "SCIENCES", "SCINDANT", "SCINTILLE", "SCISSION", "SCOLAIRE", "SCOOTERS", "SCORPIONS", "SCRIPTE", "SCRUTANT", "SCULPTER", "SÉCHEMENT", "SÉCHEUSE", "SECONDES", "SECORANT", "SECOURIR", "SECRETER", "SECTEURS", "SECTIONS", "SÉCULIÈRE", "SÉCURISER", "SÉCURITÉ", "SÉDUISANT", "SÉGRÉGATION", "SÉJOURNÉ", "SÉJOURS", "SÉLECTION", "SEMAINES", "SEMBLANT", "SEMESTRE", "SÉNATEUR", "SÉNILITÉ", "SENSIBLE", "SENSUALITÉ", "SENTEURS", "SENTIERS", "SENTIMENTAL", "SÉPARANT", "SÉPARER", "SEPTANTE", "SEPTEMBRE", "SÉQUESTRÉE", "SÉRÉNITÉ", "SERGENTS", "SÉRIEUSE", "SERINGUE", "SERMONNE", "SERPENTÉ", "SERPENTS", "SERRURES", "SERVANTE", "SERVEURS", "SERVICES", "SERVILES", "SESSIONS", "SEULEMENT", "SEVERITÉ", "SEXUELLE", "SHOPPING", "SIAMOISE", "SIÉGEANT", "SIFFLANT", "SIGNALER", "SILICONE", "SILLONNER", "SIMILAIRES", "SIMPLIFIER", "SIMULANT", "SINCÈRES", "SINGERIES", "SINGULIER", "SINISTRE", "SINUEUSE", "SIROTANT", "SITUATION", "SKATEURS", "SNOWBOARD", "SOBRE", "SOBRIÉTÉ", "SOCIALITÉ", "SOCIÉTÉS", "SOCIOLOGIE", "SOFFITES", "SOIGNANT", "SOIGNEUX", "SOLEILS", "SOLENNEL", "SOLIDAIRE", "SOLIDITÉ", "SOLISTES", "SOLITAIRE", "SOLLICITER", "SOLUTION", "SOLVABLE", "SOMMAIRE", "SOMMEILS", "SOMMITÉS", "SONGEANT", "SONGEUSE", "SONNAIES", "SONNERIE", "SONORITÉ", "SOPHISTE", "SORCIERS", "SORDIDES", "SORTANTS", "SOUCIANT", "SOUCIEUX", "SOUDAINE", "SOUDARDS", "SOUDURES", "SOUFFLANT", "SOUFFLER", "SOUHAITÉR", "SOUILLER", "SOULAGER", "SOULEVER", "SOULIGNE", "SOUMISES", "SOUPAPES", "SOUPCONS", "SOUPENTE", "SOUPIÈRE", "SOUPIRANT", "SOUPLESSE", "SOURIANT", "SOURNOIS", "SOUTENIR", "SOUTENUE", "SOUTENUS", "SOUTENUE", "SOUVENIR", "SOUVENIR", "SOUVERAIN", "SPACIEUX", "SPADRAPS", "SPATIALE", "SPATIAUX", "SPEAKERS", "SPÉCIAUX", "SPÉCIFIE", "SPECTACLE", "SPÉCULER", "SPHÉRIQUE", "SPINALES", "SPIRITUEL", "SPLENDEUR", "SPORTIFS", "SPORTIVE", "SPRINTER", "STABILISER", "STANDARD", "STARISER", "STATIQUE", "STATIONS", "STATISTIQUE", "STATUANT", "STATUFIÉ", "STEWARDS", "STIMULER", "STIPULER", "STOCKAGE", "STOÏQUES", "STRATÉGIE", "STRIDENT", "STRUCTURER", "STUDIEUX", "STUPÉFAIT", "STUPIDES", "STYLISER", "SUBIR", "SUBLIMER", "SUBORNER", "SUBSTANCE", "SUBTILES", "SUBTILITÉ", "SUBVENIR", "SUBVERSIF", "SUCCÉDER", "SUCCINCT", "SUCCOMBER", "SUCRERIE", "SUDATION", "SUFFISANTE", "SUFFIXER", "SUFFOQUER", "SUGGÉRER", "SUICIDER", "SUIVANTE", "SUIVEURS", "SUPERBE", "SUPERFLU", "SUPÉRIORITÉ", "SUPPLIER", "SUPPORTER", "SUPPOSER", "SUPRÊMES", "SUREMENT", "SURGELER", "SURMENÉE", "SURMONTER", "SURNAGER", "SURNOMMER", "SURPASSER", "SURPRENDRE", "SURSAUTER", "SURSITAIRE", "SURVEILLANT", "SURVENIR", "SURVIVRE", "SUSCEPTIBLE", "SUSCITER", "SUSPECTS", "SUSPENDRE", "SUSPENSE", "SUSTENTER", "SUZERAIN", "SYLLABES", "SYMBOLES", "SYMÉTRIE", "SYMPATHIE", "SYMPHONIE", "SYMPOSIUM", "SYMPTOME", "SYNDICATS", "SYNDROME", "SYNONYMES", "SYNOPSIS", "SYNTHÈSE", "SYSTÈMES",
		"TABASSER", "TABLEAUX", "TABLETTE", "TABOURET", "TACHETÉE", "TACITURNE", "TACTIQUE", "TAILLADE", "TAILLEURS", "TALENTS", "TALONNER", "TAMBOURS", "TANGEANT", "TANGIBLE", "TAPAGEUR", "TAPISSER", "TARDIVES", "TARIÈRES", "TAROTIER", "TARTINER", "TASSEMENT", "TATOUEUR", "TÂTONNER", "TAURINES", "TAXABLES", "TAXATION", "TECHNICIEN", "TECHNIQUE", "TEINDRE", "TEINTÉES", "TÉLÉGRAPHE", "TÉLÉPHONE", "TÉLÉVISÉ", "TELLEMENT", "TÉMÉRAIRE", "TÉMOIGNER", "TEMPÊTES", "TEMPORAIRES", "TEMPROREL", "TENABLES", "TÉNACITÉ", "TENDANCE", "TENDEURS", "TENDRESSE", "TÉNÉBREUX", "TENSIONS", "TENTANTE", "TENTATION", "TENTURES", "TERMINAL", "TERMINER", "TERNAIRE", "TERRASSE", "TERREUSE", "TERRIBLE", "TERRIENS", "TERRINES", "TERRIFIÉ", "TERRITOIRE", "TERRORISER", "TERTIAIRE", "TESTATION", "TESTEURS", "TETARDÉE", "TEXTILES", "TEXTURES", "THÈORIES", "THERAPIE", "THERMIQUE", "TIMBALES", "TIMBRÉES", "TIMONIER", "TIMORÉES", "TINTAMARRE", "TIRAIENT", "TIRAGES", "TIREUSES", "TIRETTES", "TISSAGES", "TITANESQUE", "TITULAIRE", "TOBOGGANS", "TOLÉRANT", "TOMBEAUX", "TONITRU", "TONNERRE", "TOPIQUES", "TOPONYME", "TORCHONS", "TORDANTE", "TORPILLE", "TORRÉFIÉ", "TORTURER", "TOTALITÉ", "TOUCHANT", "TOUILLER", "TOUJOURS", "TOURISME", "TOURMENT", "TOURNANT", "TOURNÉES", "TOURNOIE", "TOURTEREAUX", "TOUSSAINT", "TRACEURS", "TRACTEUR", "TRADITION", "TRAFIQUER", "TRAGÉDIE", "TRAGIQUE", "TRAHISON", "TRAINANT", "TRAINEAU", "TRAÎNÉES", "TRAITANT", "TRAÎTRES", "TRAMWAYS", "TRANCHÉE", "TRANCHER", "TRANQUILLISER", "TRANSFÉRER", "TRANSIGER", "TRANSMIS", "TRANSPORTER", "TRAQUEUSE", "TRAUMATISÉ", "TRAVAILLER", "TRAVERSÉE", "TRÉBUCHER", "TREMBLER", "TREMPAGES", "TRENTAINE", "TRÉSORER", "TRIANGLE", "TRIBUNAUX", "TRICHEUR", "TRICOLORE", "TRICOTER", "TRIDIMENSIONNEL", "TRIENNAL", "TRIFOCAL", "TRILOGIE", "TRIMESTRE", "TRIOMPHE", "TRIPLÉES", "TRIPLETTE", "TRIPOTER", "TRISTESSE", "TRIVIALES", "TROÏENNE", "TROMPEUR", "TRONQUER", "TROPICAL", "TROTTINER", "TROUBLER", "TROUILLE", "TROUSSÉE", "TROUVANT", "TRUCAGES", "TRUQUEUR", "TSUNAMI", "TUBERCULE", "TUILAGES", "TUMÉFIER", "TUMULTUE", "TUNIQUES", "TURBINES", "TURQUOISE", "TUTELLES", "TUTOYEUR", "TUYAUTER", "TYPIQUES", "TYRANNIE",
		"ULCÉRANT", "ULTÉRIEURES", "ULTIMATUM", "UNIFIÉES", "UNIFORMES", "UNIONISTE", "UNITAIRE", "UNIVERSEL", "URBANISER", "URBANISME", "URGENCES", "URINAIRE", "URINOIRS", "USTENSILE", "UTILISÉES", "UTILISER", "UTOPIQUE", "UTOPISTE",
		"VACANCES", "VACANCES", "VACILLER", "VAGABOND", "VAILLANT", "VAINCUES", "VAISELLE", "VALAISAN", "VALENCIENNE", "VALEUREUSE", "VALIDANT", "VALIDITÉ", "VALLONNÉ", "VALORISER", "VALSEURS", "VAMPIRES", "VANDALISER", "VANILLES", "VANITEUSE", "VANNERIE", "VANTARDS", "VAPOREUX", "VAPORISER", "VARIANTE", "VARIÉTÉS", "VASELINE", "VASSALES", "VAUDRAIT", "VAURIENS", "VAUTRANT", "VEGETALE", "VÉGÉTANT", "VÉHÉMENT", "VÉHICULE", "VEILLEUR", "VEINEUSE", "VÉLOCITÉ", "VENDABLE", "VENDANGE", "VENDEURS", "VENDREDI", "VENERANT", "VÉNÉRANT", "VENGEANT", "VENIMEUX", "VÉNIELLE", "VENTILATEUR", "VENTOUSE", "VERDÂTRE", "VERDICT", "VERDOYER", "VERGEURE", "VERGLACÉ", "VÉRIDIQUE", "VÉRIFIER", "VÉRIFIER", "VÉRITABLES", "VERMILLON", "VERNISSÉE", "VERONICA", "VERSANTS", "VERSEMENT", "VERSIONS", "VERTÈBRES", "VERTICAL", "VERTIGINEUSE", "VIRTUOSE", "VESTIGES", "VÉTÉRANS", "VÊTEMENT", "VÉTUSTES", "VEXATION", "VIABILITÉ", "VIANDÉES", "VIBRANTS", "VIBRANTE", "VIBREURS", "VICIEUSE", "VICTIMES", "VICTOIRE", "VIDANGES", "VIENNENT", "VIERGES", "VIEILLIR", "VIGILANT", "VIGNERON", "VIGUEURS", "VILEMENT", "VILLAGEOIS", "VINAIGRE", "VINGTAINE", "VIOLENTE", "VIOLETTE", "VIOLEUSES", "VIOLONISTE", "VIRAISON", "VIRGINAL", "VIRULENTE", "VISAGISTE", "VISCÈRES", "VISIBILITÉ", "VISIONNER", "VISITANT", "VISITEUR", "VISUALISER", "VITALITÉ", "VITRINES", "VIVACITÉ", "VIVIFIANT", "VOCALISE", "VOCATION", "VOILIERS", "VOISINER", "VOITURES", "VOLANTES", "VOLATILE", "VOLCANIQUES", "VOLENTÉ", "VOLLEYBALL", "VOLONTÉ", "VOLTIGER", "VOLUBILE", "VOLUBLES", "VOMISSANT", "VORACES", "VOTATION", "VOULOIR", "VOYAGEANT", "VOYAGEUR", "VULGAIRE", "VULNÉRABLE",
		"XÉNOPHOBE",
		"ZÉLATEUR", "ZÉLOTIQUE", "ZEPPELIN", "ZIGZAGUE", "ZINGUEUR", "ZODIAQUE", "ZONATION", "ZOOLOGIE",
	} {
		lexicon.AddWord(w)
	}

	return lexicon
}
